# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce2ee5261b72dd3d8d0aa4160990b12c79507ef02eebf8c88051cc4d4f075bd6ff22ab24a52d3f58bd826ea864231db9b7c4d7d775e2f47d546edc6c1fb177aa

test:
  secret_key_base: 569f340870dfc97d6f86b2977d21e581d6f92e558c1111c0a25e3ed4493353346721033e1bb3e6967e11891dcd8c89eac789eb11ac9e85855a417d6c01d7a853

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
